export const CAUSES_MAPPING: { [key: string]: string } = {
    "01": "Vitalisation, energy, polarity, pre-control, chakras",
    "02": "Meridian channels",
    "04": "Electrosmog",
    "05": "Geopathy",
    "06": "Acid-base balance",
    "07": "Vital substances",
    "08": "Harmful substances",
    "09": "Enzymes",
    "10": "Amino acids",
    "20": "Bacteria I",
    "21": "Bacteria II",
    "22": "Viruses I",
    "23": "Viruses II",
    "24": "Parasites I",
    "25": "Parasites II",
    "26": "Fungi I",
    "27": "Fungi II",
    "28": "Chromosomes protection",
    "29": "Chromosomes protection",
    "30": "Cells and tissue",
    "31": "Cells and tissue",
    "32": "Blood",
    "33": "Blood",
    "34": "Immune system",
    "35": "Immune system",
    "36": "Lymphatic system",
    "37": "Lymphatic system",
    "38": "Circulation",
    "39": "Circulation",
    "40": "Heart",
    "41": "Heart",
    "42": "Respiratory system",
    "43": "Respiratory system",
    "44": "Kidney / Urinary organs",
    "45": "Kidney / Urinary organs",
    "46": "Digestive system",
    "47": "Digestive system",
    "48": "Liver-gall-pancreas",
    "49": "Liver-gall-pancreas",
    "50": "Metabolism",
    "51": "Metabolism",
    "52": "Musculoskeletal system",
    "53": "Musculoskeletal system",
    "54": "Nervous system",
    "55": "Nervous system",
    "56": "Visual organ",
    "57": "Visual organ",
    "58": "Acoustic organ / Balance organ",
    "59": "Acoustic organ / Balance organ",
    "62": "Skin / Hair",
    "63": "Skin / Hair",
    "64": "Hormonal system",
    "65": "Hormonal system",
    "66": "Female sexual organs",
    "67": "Female sexual organs",
    "68": "Male sexual organs",
    "69": "Male sexual organs",
    "70": "Cause-oriented system therapy",
    "71": "Pain",
    "72": "Psyche",
    "75": "Stress",
    "76": "Tooth / Milk tooth",
    "79": "C-Module",
    "81": "Bach flowers",
    "82": "Schuessler salts",
    "83": "Resistance genes",
    "85": "Periodic table of elements",
    "95": "Own programs"
  };
  