export interface Companies {
    ticker: string;
    name: string;
  }
  
  export const companies: Companies[] = [
    { ticker: 'AAPL', name: 'Apple Inc. ' },
    { ticker: 'MSFT', name: 'Microsoft Corporation ' },
    { ticker: 'GOOG', name: 'Alphabet Inc. Class C Capital Stock' },
    { ticker: 'GOOGL', name: 'Alphabet Inc. Class A ' },
    { ticker: 'AMZN', name: 'Amazon.com Inc. ' },
    { ticker: 'BRK/A', name: 'Berkshire Hathaway Inc.' },
    { ticker: 'BRK/B', name: 'Berkshire Hathaway Inc.' },
    { ticker: 'TSLA', name: 'Tesla Inc. ' },
    { ticker: 'UNH', name: 'UnitedHealth Group Incorporated  (DE)' },
    { ticker: 'XOM', name: 'Exxon Mobil Corporation ' },
    { ticker: 'V', name: 'Visa Inc.' },
    { ticker: 'JNJ', name: 'Johnson & Johnson ' },
    { ticker: 'TSM', name: 'Taiwan Semiconductor Manufacturing Company Ltd.' },
    { ticker: 'NVDA', name: 'NVIDIA Corporation ' },
    { ticker: 'WMT', name: 'Walmart Inc. ' },
    { ticker: 'JPM', name: 'JP Morgan Chase & Co. ' },
    { ticker: 'CVX', name: 'Chevron Corporation ' },
    { ticker: 'PG', name: 'Procter & Gamble Company (The) ' },
    { ticker: 'MA', name: 'Mastercard Incorporated ' },
    { ticker: 'LLY', name: 'Eli Lilly and Company ' },
    { ticker: 'HD', name: 'Home Depot Inc. (The) ' },
    { ticker: 'META', name: 'Meta Platforms Inc. Class A ' },
    { ticker: 'BAC', name: 'Bank of America Corporation ' },
    { ticker: 'PFE', name: 'Pfizer Inc. ' },
    { ticker: 'ABBV', name: 'AbbVie Inc. ' },
    { ticker: 'KO', name: 'Coca-Cola Company (The) ' },
    { ticker: 'NVO', name: 'Novo Nordisk A/S ' },
    { ticker: 'MRK', name: 'Merck & Company Inc.  (new)' },
    { ticker: 'PEP', name: 'PepsiCo Inc. ' },
    { ticker: 'ASML', name: 'ASML Holding N.V. New York Registry Shares' },
    { ticker: 'COST', name: 'Costco Wholesale Corporation ' },
    { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc ' },
    { ticker: 'ORCL', name: 'Oracle Corporation ' },
    { ticker: 'AVGO', name: 'Broadcom Inc. ' },
    { ticker: 'BABA', name: 'Alibaba Group Holding Limited American Depositary Shares each representing eight Ordinary share' },
    { ticker: 'AZN', name: 'AstraZeneca PLC American Depositary Shares' },
    { ticker: 'SHEL', name: 'Royal Dutch Shell PLC American Depositary Shares (each representing two (2) Ordinary Shares)' },
    { ticker: 'DHR', name: 'Danaher Corporation ' },
    { ticker: 'TM', name: 'Toyota Motor Corporation ' },
    { ticker: 'MCD', name: "McDonald's Corporation " },
    { ticker: 'ACN', name: 'Accenture plc Class A Ordinary Shares (Ireland)' },
    { ticker: 'CSCO', name: 'Cisco Systems Inc.  (DE)' },
    { ticker: 'TMUS', name: 'T-Mobile US Inc. ' },
    { ticker: 'NVS', name: 'Novartis AG ' },
    { ticker: 'ABT', name: 'Abbott Laboratories ' },
    { ticker: 'WFC', name: 'Wells Fargo & Company ' },
    { ticker: 'DIS', name: 'Walt Disney Company (The) ' },
    { ticker: 'NKE', name: 'Nike Inc. ' },
    { ticker: 'COP', name: 'ConocoPhillips ' },
    { ticker: 'LIN', name: 'Linde plc Ordinary Share' },
    { ticker: 'NEE', name: 'NextEra Energy Inc. ' },
    { ticker: 'CRM', name: 'Salesforce Inc. ' },
    { ticker: 'TXN', name: 'Texas Instruments Incorporated ' },
    { ticker: 'VZ', name: 'Verizon Communications Inc. ' },
    { ticker: 'ADBE', name: 'Adobe Inc. ' },
    { ticker: 'BMY', name: 'Bristol-Myers Squibb Company ' },
    { ticker: 'UPS', name: 'United Parcel Service Inc. ' },
    { ticker: 'MS', name: 'Morgan Stanley ' },
    { ticker: 'AMGN', name: 'Amgen Inc. ' },
    { ticker: 'CMCSA', name: 'Comcast Corporation Class A ' },
    { ticker: 'BHP', name: 'BHP Group Limited American Depositary Shares (Each representing two Ordinary Shares)' },
    { ticker: 'TTE', name: 'TotalEnergies SE' },
    { ticker: 'PM', name: 'Philip Morris International Inc ' },
    { ticker: 'PM', name: 'Philip Morris International Inc ' },
  { ticker: 'SCHW', name: 'Charles Schwab Corporation (The) ' },
  { ticker: 'HON', name: 'Honeywell International Inc. ' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated ' },
  { ticker: 'RY', name: 'Royal Bank Of Canada ' },
  { ticker: 'NFLX', name: 'Netflix Inc. ' },
  { ticker: 'RTX', name: 'Raytheon Technologies Corporation ' },
  { ticker: 'T', name: 'AT&T Inc.' },
  { ticker: 'UNP', name: 'Union Pacific Corporation ' },
  { ticker: 'GS', name: 'Goldman Sachs Group Inc. (The) ' },
  { ticker: 'IBM', name: 'International Business Machines Corporation ' },
  { ticker: 'HDB', name: 'HDFC Bank Limited ' },
  { ticker: 'SAP', name: 'SAP  SE ADS' },
  { ticker: 'INTC', name: 'Intel Corporation ' },
  { ticker: 'LOW', name: "Lowe's Companies Inc. " },
  { ticker: 'CVS', name: 'CVS Health Corporation ' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc. ' },
  { ticker: 'CAT', name: 'Caterpillar Inc. ' },
  { ticker: 'DE', name: 'Deere & Company ' },
  { ticker: 'UL', name: 'Unilever PLC ' },
  { ticker: 'LMT', name: 'Lockheed Martin Corporation ' },
  { ticker: 'TD', name: 'Toronto Dominion Bank (The) ' },
  { ticker: 'INTU', name: 'Intuit Inc. ' },
  { ticker: 'AXP', name: 'American Express Company ' },
  { ticker: 'ELV', name: 'Elevance Health Inc. ' },
  { ticker: 'SPGI', name: 'S&P Global Inc. ' },
  { ticker: 'HSBC', name: 'HSBC Holdings plc. ' },
  { ticker: 'SBUX', name: 'Starbucks Corporation ' },
  { ticker: 'BLK', name: 'BlackRock Inc. ' },
  { ticker: 'EQNR', name: 'Equinor ASA' },
  { ticker: 'MDT', name: 'Medtronic plc. Ordinary Shares' },
  { ticker: 'BUD', name: 'Anheuser-Busch Inbev SA Sponsored ADR (Belgium)' },
  { ticker: 'SNY', name: 'Sanofi ADS' },
  { ticker: 'AMX', name: 'America Movil S.A.B. de C.V. American Depository Receipt Series L' },
  { ticker: 'RIO', name: 'Rio Tinto Plc ' },
  { ticker: 'AMOV', name: 'America Movil S.A.B. de C.V. Class A American Depositary Shares' },
  { ticker: 'PLD', name: 'Prologis Inc. ' },
  { ticker: 'PYPL', name: 'PayPal Holdings Inc. ' },
];