export interface Currency {
    code: string;
    name: string;
}

export const currencies: Currency[] = [
    { code: 'USD', name: 'United States Dollar' },
    { code: 'EUR', name: 'Euro' },
    { code: 'JPY', name: 'Japanese Yen' },
    { code: 'CNY', name: 'Chinese Yuan' },
    { code: 'AUD', name: 'Australian Dollar' },
    { code: 'CAD', name: 'Canadian Dollar' },
    { code: 'CHF', name: 'Swiss Franc' },
    { code: 'SEK', name: 'Swedish Krona' },
    { code: 'NZD', name: 'New Zealand Dollar' },
    { code: 'KRW', name: 'South Korean Won' },
    { code: 'SGD', name: 'Singapore Dollar' },
    { code: 'NOK', name: 'Norwegian Krone' },
    { code: 'MXN', name: 'Mexican Peso' },
    { code: 'INR', name: 'Indian Rupee' },
    { code: 'RUB', name: 'Russian Ruble' },
    { code: 'BRL', name: 'Brazilian Real' },
    { code: 'ZAR', name: 'South African Rand' },
    { code: 'HKD', name: 'Hong Kong Dollar' },
    { code: 'TRY', name: 'Turkish Lira' },
    { code: 'THB', name: 'Thai Baht' },
    { code: 'IDR', name: 'Indonesian Rupiah' },
    { code: 'MYR', name: 'Malaysian Ringgit' },
    { code: 'PHP', name: 'Philippine Peso' },
    { code: 'PLN', name: 'Polish Zloty' },
    { code: 'HUF', name: 'Hungarian Forint' },
    { code: 'CZK', name: 'Czech Koruna' },
    { code: 'ILS', name: 'Israeli New Shekel' },
    { code: 'DKK', name: 'Danish Krone' },
    { code: 'SAR', name: 'Saudi Riyal' },
    { code: 'AED', name: 'United Arab Emirates Dirham' },
    { code: 'CLP', name: 'Chilean Peso' },
    { code: 'KWD', name: 'Kuwaiti Dinar' },
    { code: 'QAR', name: 'Qatari Riyal' },
    { code: 'ARS', name: 'Argentine Peso' },
    { code: 'TWD', name: 'Taiwan New Dollar' },
    { code: 'VND', name: 'Vietnamese Dong' },
    { code: 'EGP', name: 'Egyptian Pound' },
    { code: 'UAH', name: 'Ukrainian Hryvnia' },
    { code: 'NGN', name: 'Nigerian Naira' },
    { code: 'BDT', name: 'Bangladeshi Taka' },
    { code: 'PKR', name: 'Pakistani Rupee' },
    { code: 'COP', name: 'Colombian Peso' },
    { code: 'IRR', name: 'Iranian Rial' },
    { code: 'GHS', name: 'Ghanaian Cedi' },
    { code: 'IQD', name: 'Iraqi Dinar' },
    { code: 'OMR', name: 'Omani Rial' },
    { code: 'KES', name: 'Kenyan Shilling' },
    { code: 'XAF', name: 'Central African CFA Franc' },
    { code: 'UGX', name: 'Ugandan Shilling' },
    { code: 'DZD', name: 'Algerian Dinar' },
    { code: 'KZT', name: 'Kazakhstani Tenge' },
    { code: 'BYN', name: 'Belarusian Ruble' },
    { code: 'TZS', name: 'Tanzanian Shilling' },
    { code: 'TND', name: 'Tunisian Dinar' },
    { code: 'LBP', name: 'Lebanese Pound' },
    { code: 'GEL', name: 'Georgian Lari' },
    { code: 'XOF', name: 'West African CFA Franc' },
    { code: 'SDG', name: 'Sudanese Pound' },
    { code: 'MAD', name: 'Moroccan Dirham' },
    { code: 'MZN', name: 'Mozambican Metical' },
    { code: 'AFN', name: 'Afghan Afghani' },
    { code: 'XCD', name: 'East Caribbean Dollar' },
    { code: 'NPR', name: 'Nepalese Rupee' },
]
